//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musterije
    {
        public int Id_musterije { get; set; }
        public string Prezime { get; set; }
        public string Ime { get; set; }
        public string Telefon { get; set; }
    }
}
